// HTML Descriptions Update Script — KHOGA Products (correct handles)
// Run with: mongosh khoga_store backend/update_descriptions_html.js

const descriptions = {
  "premium-espresso-bundle": `<p><strong>The Full Espresso Experience.</strong></p><p>Everything you need to brew café-quality espresso at home. Our <strong>Premium Espresso Bundle</strong> pairs our signature 100% Arabica espresso with the essential tools to craft the perfect shot every time.</p><p><strong>Inside the Bundle:</strong></p><ul><li><strong>3-Cup Moka Pot:</strong> A large-capacity, stovetop espresso maker built from premium aluminium — delivers a rich, full-bodied extraction with every brew.</li><li><strong>Premium Espresso (200g):</strong> Our signature House Blend — 100% Arabica beans, medium roasted for a balanced, smooth crema with notes of dark chocolate and caramel.</li><li><strong>Luxury Gift Box:</strong> Presented in our signature KHOGA gift box — perfect as a gift or a personal treat.</li></ul><p><strong>Why Choose This Bundle?</strong> Skip the café. Whether you're a morning ritual purist or an espresso connoisseur, this bundle gives you everything to craft the perfect shot from the comfort of your home.</p>`,

  "premium-turkish-coffee-bundle": `<p><strong>The Ultimate Expression of Turkish Coffee Craftsmanship.</strong></p><p>Experience the perfect harmony of tradition and luxury with our <strong>Premium Turkish Coffee Bundle</strong>. Designed for true connoisseurs, this set offers a fully customizable journey through the rich world of authentic Turkish coffee, paired with an elegant touch of modern design.</p><p><strong>What's Inside the Box:</strong></p><ul><li><strong>Two Premium 200g Canisters (400g Total):</strong> Tailor your bundle by selecting your preferred blend for each canister:<ul><li><strong>Plain (Sada):</strong> Pure, unadulterated 100% Arabica — for those who appreciate the essence of the bean.</li><li><strong>Spiced (Mahwog):</strong> Expertly blended with premium cardamom for a rich, traditional aroma.</li><li><strong>Your Choice of Roast:</strong> Light Roast for brightness, or Medium Roast for balance.</li></ul></li><li><strong>Elite Porcelain Cup &amp; Saucer:</strong> A high-end, vibrant yellow porcelain set with a glossy finish and modern silhouette. Retains heat perfectly for every sip.</li><li><strong>Signature Luxury Gift Box:</strong> Nestled in our "Love is Coffee" black gift box with elegant Arabic calligraphy and premium protective filling.</li></ul><p><strong>Why Choose This Bundle?</strong> This isn't just coffee — it's a ritual. Whether you prefer a mix of roasts or a specific blend, this bundle gives you the flexibility to create your signature coffee moment.</p>`,

  "artisanal-morning-mini-bundle": `<p><strong>Your Perfect Morning, Simplified.</strong></p><p>Start every day right with the <strong>Artisanal Morning Mini Bundle</strong> — a curated selection of KHOGA's finest, designed to bring warmth, flavour, and elegance to your morning routine.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Premium Coffee (100g):</strong> A carefully selected blend to kickstart your morning with rich, aromatic depth.</li><li><strong>Artisan Mug:</strong> A handcrafted stoneware mug — the ideal vessel for your daily brew.</li><li><strong>Luxury Mini Gift Box:</strong> Beautifully packaged for gifting or personal indulgence.</li></ul><p><strong>Why Choose This Bundle?</strong> Compact, complete, and crafted with care — everything you need to elevate your morning ritual in one beautifully presented box.</p>`,

  "ice-bloom-premium-bundle": `<p><strong>Coffee, Reimagined for Summer.</strong></p><p>The <strong>Ice &amp; Bloom Premium Bundle</strong> is your all-in-one cold coffee experience — crafted for those who crave the bold flavour of premium coffee, chilled and refreshed.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Premium Cold Brew Blend (200g):</strong> A specially selected coffee optimised for cold extraction — smooth, low-acid, with a naturally sweet finish.</li><li><strong>Double-Wall Glass Cup:</strong> Keeps your iced coffee perfectly chilled without condensation.</li><li><strong>Handheld Milk Frother:</strong> Whip up cold foam, frothy milk, or creamy cold lattes in seconds.</li><li><strong>Luxury Gift Box:</strong> Presented in our signature KHOGA packaging — ready to gift or enjoy.</li></ul><p><strong>Why Choose This Bundle?</strong> Everything you need to craft café-style cold coffee drinks at home — from iced lattes to cold brew, all in one premium set.</p>`,

  "instant-coffee-bundle-the-bubble-edition-v-2": `<p><strong>Bold Coffee. Zero Effort. Maximum Flavour.</strong></p><p>The <strong>Instant Coffee Bundle – The Bubble Edition (V.2)</strong> is for the coffee lover who demands rich taste without the wait. Our premium instant blends are crafted from 100% quality coffee — no fillers, no compromise.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Instant Coffee Gold (1 tin):</strong> Our premium gold-grade instant coffee — silky, refined, and intensely aromatic.</li><li><strong>Instant Coffee Classic (1 tin):</strong> Bold, full-bodied, and deeply satisfying — the everyday essential.</li><li><strong>Luxury Gift Box:</strong> Beautifully presented in the KHOGA signature Bubble Edition box.</li></ul><p><strong>Why Choose This Bundle?</strong> Two of our most-loved instant coffees together in one gift-ready package. Perfect for gifting, travel, or upgrading your desk coffee game.</p>`,

  "the-marshmallow-cloud-bundle": `<p><strong>Indulge in the Softer Side of Coffee.</strong></p><p>The <strong>Marshmallow Cloud Bundle</strong> is a dreamy, dessert-inspired coffee experience for those who love their brew with a touch of sweetness and whimsy.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Premium Instant Coffee Blend:</strong> A smooth, creamy coffee base that pairs beautifully with sweet flavours.</li><li><strong>Gourmet Marshmallows:</strong> Artisan-quality, fluffy marshmallows — melt them into your coffee or hot chocolate for a cloud-like finish.</li><li><strong>Luxury Hot Chocolate Mix:</strong> Velvety, rich, and indulgent — the perfect pairing for a marshmallow topping.</li><li><strong>Signature Gift Box:</strong> Presented in our whimsical KHOGA gift packaging.</li></ul><p><strong>Why Choose This Bundle?</strong> A treat for yourself or the perfect gift for someone who loves comfort drinks. Curl up, stir in the marshmallows, and float away.</p>`,

  "the-cozy-haven-bundle": `<p><strong>Your Complete Cozy Coffee Escape.</strong></p><p>The <strong>Cozy Haven Bundle</strong> is designed for those moments when you need to slow down, wrap up, and savour every sip. A carefully curated collection of KHOGA's warmest, most comforting products.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Premium Hot Chocolate Mix:</strong> Our richest, most velvety drinking chocolate — perfect for cold evenings.</li><li><strong>Cozy Mug:</strong> A warm-toned, tactile mug designed for comfort-first coffee moments.</li><li><strong>Premium Instant Coffee:</strong> Bold and satisfying — for when you need warmth fast.</li><li><strong>Luxury Gift Box:</strong> Wrapped in our signature KHOGA packaging with cozy-themed accents.</li></ul><p><strong>Why Choose This Bundle?</strong> Sometimes self-care looks like a hot drink in a beautiful mug. The Cozy Haven Bundle is your invitation to stop, breathe, and enjoy the moment.</p>`,

  "instant-coffee-bundle": `<p><strong>The Instant Coffee Essentials.</strong></p><p>The <strong>KHOGA Instant Coffee Bundle</strong> brings together our best instant coffee selections — bold, smooth, and ready in seconds. Perfect for the home, office, or on-the-go.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Instant Coffee Gold:</strong> Premium gold-grade instant — smooth, aromatic, and refined.</li><li><strong>Instant Coffee Classic:</strong> Full-bodied and bold — the dependable everyday essential.</li><li><strong>Luxury Gift Box:</strong> Presented in KHOGA signature packaging.</li></ul><p><strong>Why Choose This Bundle?</strong> The simplest way to always have great coffee ready — no equipment, no waiting. Just pour and enjoy.</p>`,

  "mix-flavor-bundle-the-trio": `<p><strong>Three Flavours. One Ultimate Bundle.</strong></p><p>Can't choose just one? <strong>The Trio – Mix Flavor Bundle</strong> brings together three of KHOGA's most popular coffee flavours — a perfect way to explore the full range or share the love with someone special.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Flavour 1 – Classic:</strong> Bold, full-bodied, and pure — the original KHOGA experience.</li><li><strong>Flavour 2 – Hazelnut:</strong> Warm, roasted, and naturally sweet — our most popular flavoured blend.</li><li><strong>Flavour 3 – Caramel:</strong> Smooth, buttery, and indulgent — the crowd-pleaser.</li><li><strong>Luxury Gift Box:</strong> All three presented in a beautifully curated KHOGA gift set.</li></ul><p><strong>Why Choose The Trio?</strong> Explore, compare, and discover your new favourite. The Trio is the perfect intro to the KHOGA flavour universe — or the ideal gift for the coffee lover in your life.</p>`,

  "you-are-my-coffee-bundle": `<p><strong>Because Love is Best Expressed in Coffee.</strong></p><p>The <strong>"You Are My Coffee" Premium Gift Box</strong> is KHOGA's most romantic, heartfelt offering — a beautifully curated gift set for the person who means everything to you. Whether for a birthday, anniversary, or just because — this gift says it all.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Premium Coffee Selection:</strong> Our finest blends, chosen to delight any coffee lover.</li><li><strong>Artisan Mug:</strong> A beautifully crafted mug — a daily reminder of your thoughtfulness.</li><li><strong>"You Are My Coffee" Gift Box:</strong> Packaged in our signature love-themed box with heartfelt typography and premium finishing.</li></ul><p><strong>Why Give This Gift?</strong> Coffee is love made drinkable. This gift box makes that sentiment tangible — beautiful, meaningful, and genuinely delicious.</p>`,

  "instant-coffee-gold": `<p><strong>Premium Instant Coffee — Elevated.</strong></p><p><strong>Khoga Instant Coffee – Premium Gold</strong> is our finest instant coffee — crafted for those who refuse to compromise on quality, even when time is short.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Grade:</strong> Premium Gold — the highest tier in our instant coffee range.</li><li><strong>Flavour Profile:</strong> Rich, smooth, and intensely aromatic with a velvety finish and no bitter aftertaste.</li><li><strong>Dissolves Instantly:</strong> In hot or cold water — café-quality in seconds.</li><li><strong>Versatile:</strong> Perfect for espresso-style shots, lattes, iced coffee, or dalgona whipped coffee.</li><li><strong>Tin Packaging:</strong> Preserved in an airtight premium tin to lock in freshness and aroma.</li></ul><p><strong>Why Choose Gold?</strong> When your mornings demand the best — Khoga Gold delivers a premium instant experience that rivals any café brew.</p>`,

  "instant-coffee-classic": `<p><strong>Bold. Reliable. Effortlessly Good.</strong></p><p><strong>Khoga Instant Coffee – Premium Classic</strong> is the everyday essential for the discerning coffee lover. Rich, full-bodied flavour — ready in seconds.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Grade:</strong> Premium Classic — expertly crafted for consistent, satisfying results.</li><li><strong>Flavour Profile:</strong> Deep, bold, and full-bodied with a smooth, clean finish.</li><li><strong>Dissolves Instantly:</strong> In hot or cold water — no brewing equipment needed.</li><li><strong>Versatile:</strong> Ideal for espresso shots, lattes, iced coffee, or whipped coffee creations.</li><li><strong>Tin Packaging:</strong> Airtight tin preserves peak freshness from the first spoon to the last.</li></ul><p><strong>Why Choose Classic?</strong> The dependable daily driver — a bold, premium instant coffee that never lets you down.</p>`,

  "instant-coffee-3x1": `<p><strong>Coffee, Cream &amp; Sugar — Perfectly Balanced in One.</strong></p><p><strong>Khoga Coffee &amp; Cream – Premium 3-in-1</strong> is the complete instant coffee experience. Rich coffee, smooth cream, and just the right touch of sweetness — blended to perfection.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium 3-in-1 Instant Blend — coffee, creamer, and sugar in a single sachet.</li><li><strong>Flavour Profile:</strong> Creamy, smooth, and balanced — satisfying without being overly sweet.</li><li><strong>Preparation:</strong> Just add hot water and stir — ready in under 30 seconds.</li><li><strong>Portability:</strong> Individual sachets ideal for travel, the office, or home.</li></ul><p><strong>Why Choose This?</strong> No measuring, no mess — just pour, stir, and enjoy a perfectly balanced, creamy coffee anywhere you are.</p>`,

  "instant-coffee-hazelnut-3x1": `<p><strong>Hazelnut Warmth in Every Sip.</strong></p><p><strong>Khoga Rich Hazelnut – Premium 3-in-1</strong> brings together the bold depth of premium coffee with the warm, nutty sweetness of roasted hazelnut — all in one convenient blend.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium 3-in-1 Hazelnut Instant Blend — coffee, creamer, and hazelnut flavour.</li><li><strong>Flavour Profile:</strong> Warm hazelnut, smooth cream, and rich coffee — indulgent yet perfectly balanced.</li><li><strong>Preparation:</strong> Add hot water, stir, and enjoy in under 30 seconds.</li><li><strong>Portability:</strong> Individual sachets for on-the-go enjoyment.</li></ul><p><strong>Why Choose Hazelnut?</strong> For those who love a flavoured coffee with depth — not too sweet, not too strong. A daily indulgence that feels like a treat every time.</p>`,

  "instant-coffee-caramel-3x1": `<p><strong>Caramel Coffee Bliss — Instantly.</strong></p><p><strong>Khoga Creamy Caramel – Premium 3-in-1</strong> combines premium instant coffee with smooth creamer and warm caramel flavour — the ultimate indulgent instant blend for caramel lovers.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium 3-in-1 Caramel Instant Blend.</li><li><strong>Flavour Profile:</strong> Rich coffee with buttery caramel sweetness and a creamy finish.</li><li><strong>Preparation:</strong> Add hot water and stir — ready in 30 seconds.</li><li><strong>Portability:</strong> Individual sachets — perfect for anywhere, anytime.</li></ul><p><strong>Why Choose Caramel?</strong> Warm, sweet, and deeply satisfying — the caramel blend turns your everyday coffee moment into a small daily luxury.</p>`,

  "instant-coffee-creamer": `<p><strong>Elevate Every Cup.</strong></p><p><strong>Khoga Richy &amp; Creamy – Premium Coffee Creamer &amp; Enhancer</strong> is the secret ingredient to a smoother, richer, more indulgent cup of coffee. Add it to any coffee — instant, filter, or espresso — for an instant upgrade.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium powdered coffee creamer and flavour enhancer.</li><li><strong>Effect:</strong> Adds body, smoothness, and a naturally creamy sweetness without overpowering the coffee.</li><li><strong>Compatibility:</strong> Works with all coffee types — instant, filter, Turkish, espresso, and hot chocolate.</li><li><strong>Convenience:</strong> Measured scoops — no refrigeration needed.</li></ul><p><strong>Why Choose Richy &amp; Creamy?</strong> A small addition with a big impact — transforms any cup into a richer, more satisfying coffee experience.</p>`,

  "turkish-coffee-200g": `<p><strong>The Purest Expression of Turkish Coffee.</strong></p><p><strong>KHOGA Premium Turkish Coffee</strong> is crafted from 100% Arabica beans, finely ground to the traditional Turkish powder — delivering an authentic, full-bodied brew with a rich, velvety crema.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Blend:</strong> 100% Premium Arabica — no robusta, no fillers.</li><li><strong>Grind:</strong> Extra-fine Turkish grind for authentic pot brewing.</li><li><strong>Roast:</strong> Available in Light or Medium Roast.</li><li><strong>Flavour Profile:</strong> Rich, earthy, and deeply aromatic with a naturally sweet finish.</li><li><strong>Weight:</strong> 200g — approximately 20–25 cups.</li></ul><p><strong>Brewing Tip:</strong> Use a traditional kanaka or cezve with cold water. Add sugar before boiling for the most authentic result.</p>`,

  "turkish-coffee-cardamom-200g": `<p><strong>The Classic Cardamom Ritual.</strong></p><p><strong>KHOGA Premium Turkish Coffee – Cardamom</strong> is a time-honoured blend of 100% Arabica coffee infused with premium cardamom — delivering the iconic Gulf and Levantine coffee experience with every cup.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Blend:</strong> 100% Arabica with premium ground cardamom.</li><li><strong>Grind:</strong> Extra-fine Turkish grind.</li><li><strong>Flavour Profile:</strong> Bold coffee depth with warm, floral cardamom spice — aromatic and distinctively traditional.</li><li><strong>Weight:</strong> 200g.</li></ul><p><strong>Why This Blend?</strong> Cardamom and coffee are an ancient pairing — warming, aromatic, and unmistakably Middle Eastern. Each cup is a cultural experience in a small, elegant serving.</p>`,

  "turkish-coffee-mastic-cardamom-200g": `<p><strong>Two Legends, One Extraordinary Cup.</strong></p><p><strong>KHOGA Premium Turkish Coffee – Cardamom &amp; Mastic</strong> brings together two of the most revered flavour traditions of the Eastern Mediterranean — premium cardamom and authentic Greek mastic — in one beautifully complex blend.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Blend:</strong> 100% Arabica with cardamom and Greek mastic resin.</li><li><strong>Flavour Profile:</strong> Bold coffee, floral cardamom warmth, and a cool, resinous mastic note — layered, aromatic, and deeply complex.</li><li><strong>Grind:</strong> Extra-fine Turkish grind.</li><li><strong>Weight:</strong> 200g.</li></ul><p><strong>Why This Blend?</strong> For the adventurous coffee lover who wants more than a simple cup — this is a journey through the flavours of the Levant and the Mediterranean in a single sip.</p>`,

  "turkish-coffee-mastic-200g": `<p><strong>The Taste of the Mediterranean.</strong></p><p><strong>KHOGA Premium Turkish Coffee – Greek Mastic</strong> pairs our finest Arabica coffee with authentic Greek mastic resin — a rare, pine-scented ingredient prized across the Eastern Mediterranean for centuries.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Blend:</strong> 100% Arabica with authentic Greek mastic.</li><li><strong>Flavour Profile:</strong> Smooth coffee with a subtle, resinous pine note and a uniquely refreshing finish.</li><li><strong>Grind:</strong> Extra-fine Turkish grind.</li><li><strong>Weight:</strong> 200g.</li></ul><p><strong>Why Mastic?</strong> A rare and sophisticated pairing — mastic adds cool, herbal complexity to the deep richness of Turkish coffee. Beloved in Greece, Cyprus, and across the Levant.</p>`,

  "hazelnut-coffee": `<p><strong>Tradition Meets Indulgence.</strong></p><p><strong>KHOGA Premium Turkish Coffee – Hazelnut</strong> is a luxurious blend of authentic Turkish coffee and warm roasted hazelnut — for those who love rich coffee with a naturally sweet, nutty twist.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Blend:</strong> 100% Arabica with premium roasted hazelnut.</li><li><strong>Flavour Profile:</strong> Deep, bold coffee with warm, roasted hazelnut warmth — smooth and indulgent.</li><li><strong>Grind:</strong> Extra-fine Turkish grind.</li><li><strong>Weight:</strong> 200g.</li></ul><p><strong>Why Hazelnut?</strong> The nutty sweetness softens the intensity of Turkish coffee, creating a more approachable yet deeply satisfying cup — perfect for those who want flavour and richness in equal measure.</p>`,

  "espresso-beans-200g": `<p><strong>The Art of the Perfect Shot.</strong></p><p><strong>KHOGA Premium Espresso – House Blend</strong> is our signature 100% Arabica espresso, medium roasted to perfection. Crafted for Moka Pot, espresso machine, or AeroPress — designed to produce a rich crema and a balanced, complex extraction.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Origin:</strong> 100% Arabica — single-origin quality, house-blend consistency.</li><li><strong>Roast:</strong> Medium — balances bright acidity with deep body and sweetness.</li><li><strong>Grind:</strong> Pre-ground to espresso fineness — optimised for Moka Pot and espresso machines.</li><li><strong>Flavour Profile:</strong> Notes of dark chocolate, caramel, and a subtle citrus brightness with a smooth, lingering finish.</li><li><strong>Weight:</strong> 200g — approximately 20 double shots.</li></ul><p><strong>Brewing Tip:</strong> For best results, use freshly boiled water (not boiling) in your Moka Pot and remove from heat the moment you hear the first splutter.</p>`,

  "the-artisan-speckled-stone-mug-earth-edition": `<p><strong>Nature, Captured in Clay.</strong></p><p>The <strong>Artisan Speckled Stone Mug – Earth Edition</strong> is a celebration of organic texture and earthy warmth. Handcrafted from premium stoneware, each mug is uniquely speckled — no two pieces are identical.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Premium artisan stoneware — microwave and dishwasher safe.</li><li><strong>Finish:</strong> Earthy, speckled glaze with a matte-to-satin texture — inspired by natural stone and soil tones.</li><li><strong>Capacity:</strong> 350ml — ideal for a generous latte, flat white, or morning tea.</li><li><strong>Geometry:</strong> Slightly tapered form with a comfortable loop handle — ergonomic and elegant.</li><li><strong>Lifestyle:</strong> Pairs beautifully with wooden surfaces, linen, and natural home aesthetics.</li></ul><p><strong>Why This Mug?</strong> A functional piece of art — rugged enough for daily use, beautiful enough to display. The Earth Edition brings the outdoors to your coffee ritual.</p>`,

  "artisan-speckled-moss-mug-the-pure-edition": `<p><strong>The Quiet Luxury of Moss &amp; Stone.</strong></p><p>The <strong>Artisan Speckled Moss Mug – Pure Edition</strong> blends organic texture with a cool, mossy palette — a serene, nature-inspired piece for the considered coffee drinker.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Premium artisan stoneware — microwave and dishwasher safe.</li><li><strong>Finish:</strong> Soft moss-green speckled glaze with a smooth satin surface.</li><li><strong>Capacity:</strong> 350ml.</li><li><strong>Geometry:</strong> Classic loop handle with a gently curved body — comfortable and refined.</li><li><strong>Lifestyle:</strong> Perfect for minimalist, Japandi, or Scandinavian-inspired interiors.</li></ul><p><strong>Why This Mug?</strong> Earthy yet refined, tactile yet smooth — the Moss Edition is for those who find beauty in subtlety and elegance in simplicity.</p>`,

  "charcoal-shadow-ribbed-mug": `<p><strong>Dark, Bold, Unmistakable.</strong></p><p>The <strong>Charcoal Shadow Ribbed Mug</strong> is designed for those who take their coffee — and their aesthetics — seriously. Deep charcoal tones and precise vertical ribbing create a mug that commands attention.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Deep charcoal matte glaze — rich, dramatic, and fingerprint-resistant.</li><li><strong>Build:</strong> Dense stoneware — excellent heat retention for a slow, leisurely coffee moment.</li><li><strong>Geometry:</strong> Precision-spaced vertical ribbing for a confident, secure grip.</li><li><strong>Capacity:</strong> 350ml.</li><li><strong>Lifestyle:</strong> Ideal for dark, moody aesthetics — pairs perfectly with black interiors, dark wood, and industrial design.</li></ul><p><strong>Why This Mug?</strong> Bold without being loud. The Charcoal Shadow is for the person who knows exactly what they want — and settles for nothing less.</p>`,

  "ash-grey-ribbed-mug": `<p><strong>The Essence of Minimalist Refinement.</strong></p><p>The <strong>Ash Grey Ribbed Mug</strong> is a masterclass in understated elegance. A clean, neutral palette and tactile ribbed stoneware construction — for those who seek professional-grade quality with a timeless, serene aesthetic.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Sophisticated ash-grey matte surface that resists fingerprints and stays pristine.</li><li><strong>Build:</strong> Robust stoneware construction built for longevity and daily performance.</li><li><strong>Geometry:</strong> Perfectly spaced vertical fluting that offers a sophisticated grip.</li><li><strong>Capacity:</strong> 350ml.</li><li><strong>Lifestyle:</strong> Seamlessly fits into any workspace or home coffee station.</li></ul><p><strong>Why This Mug?</strong> Sometimes the most refined choice is the quietest one. Ash Grey pairs with everything and elevates any setting without demanding attention.</p>`,

  "creamy-custard-ribbed-mug": `<p><strong>Warmth in Every Detail.</strong></p><p>The <strong>Creamy Custard Ribbed Mug</strong> brings gentle warmth and soft luxury to your daily coffee ritual. A warm, custard-yellow tone that feels like a hug — perfect for slow mornings and cozy afternoons.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Soft, creamy custard matte glaze — warm, inviting, and beautifully tactile.</li><li><strong>Build:</strong> Premium ribbed stoneware — durable, heat-retaining, and dishwasher safe.</li><li><strong>Geometry:</strong> Clean vertical ribbing with a comfortable loop handle.</li><li><strong>Capacity:</strong> 350ml.</li><li><strong>Lifestyle:</strong> Perfect for cottagecore, warm-toned, or Scandinavian home aesthetics.</li></ul><p><strong>Why This Mug?</strong> A colour that makes every morning feel a little softer. The Creamy Custard is the mug you reach for when you want comfort as much as coffee.</p>`,

  "premium-porcelain-mug": `<p><strong>Porcelain Precision, Daily Comfort.</strong></p><p>The <strong>Ribbed Porcelain Comfort Mug</strong> brings the refinement of fine porcelain to your everyday coffee ritual. Lighter than stoneware, smoother to the touch, and beautifully glazed.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Fine porcelain — lightweight, non-porous, and ultra-smooth.</li><li><strong>Finish:</strong> Clean glaze with subtle ribbing — elegant and understated.</li><li><strong>Capacity:</strong> 320ml — ideal for espresso-style drinks, flat whites, and cortados.</li><li><strong>Build:</strong> Chip-resistant porcelain — microwave and dishwasher safe.</li><li><strong>Lifestyle:</strong> The everyday refined choice — works equally well in a minimalist kitchen or a formal table setting.</li></ul><p><strong>Why Porcelain?</strong> Porcelain offers a cleaner, lighter experience than stoneware — no flavour transfer, no porous surface. Pure coffee, pure taste.</p>`,

  "plain-hot-chocolate": `<p><strong>Rich, Velvety, Timeless.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Classic</strong> is the definitive hot chocolate experience. Made from premium cacao with a perfectly balanced sweetness — indulgent without being excessive.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium drinking chocolate — not a cocoa powder mix.</li><li><strong>Flavour Profile:</strong> Deep, rich cacao with smooth sweetness and a velvety finish.</li><li><strong>Preparation:</strong> Mix with hot milk (or water) and stir — ready in 60 seconds.</li><li><strong>Texture:</strong> Thick, luxurious body that coats the palate beautifully.</li></ul><p><strong>Why Classic?</strong> Because perfection doesn't need embellishment. The Classic is the benchmark — everything a hot chocolate should be.</p>`,

  "hot-chocolate-hazelnut-250g": `<p><strong>Hazelnut Dreams in a Cup.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Hazelnut</strong> combines the deep richness of premium cacao with warm, roasted hazelnut — a beloved pairing that feels indulgent with every sip.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium hazelnut drinking chocolate.</li><li><strong>Flavour Profile:</strong> Rich dark chocolate meets warm, roasted hazelnut — smooth, nutty, and deeply satisfying.</li><li><strong>Preparation:</strong> Mix with hot milk for a creamy, café-style hot chocolate.</li><li><strong>Best Paired With:</strong> A sprinkle of crushed hazelnuts on top for extra indulgence.</li></ul><p><strong>Why Hazelnut?</strong> Chocolate and hazelnut are one of the great flavour partnerships — warming, rich, and naturally sweet.</p>`,

  "hot-chocolate-caramel-250g": `<p><strong>Silky Caramel Meets Velvety Chocolate.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Caramel</strong> wraps the deep warmth of premium cacao in a golden caramel embrace — sweet, complex, and endlessly comforting.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium caramel drinking chocolate.</li><li><strong>Flavour Profile:</strong> Rich chocolate base with a buttery caramel sweetness and a smooth, lingering finish.</li><li><strong>Preparation:</strong> Stir into hot milk for a thick, indulgent caramel hot chocolate.</li><li><strong>Best Paired With:</strong> A drizzle of caramel sauce and a pinch of sea salt on top.</li></ul><p><strong>Why Caramel?</strong> Caramel adds a buttery, complex sweetness that elevates chocolate from comforting to genuinely indulgent. This is dessert in a mug.</p>`,

  "hot-chocolate-strawberry-250g": `<p><strong>Summer Berries, Winter Warmth.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Sparkle Strawberry</strong> is a playful, vibrant twist on the classic — rich chocolate meets fresh, fruity strawberry in a surprisingly elegant combination.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium strawberry-infused drinking chocolate with shimmer.</li><li><strong>Flavour Profile:</strong> Smooth chocolate with bright, natural strawberry sweetness and a subtle sparkle finish.</li><li><strong>Preparation:</strong> Mix with hot milk — stir well to activate the shimmer.</li><li><strong>Best For:</strong> Gifting, celebrations, and anyone who loves fruit-chocolate pairings.</li></ul><p><strong>Why Sparkle Strawberry?</strong> Because sometimes your hot chocolate should be as joyful as it is delicious. This one sparkles — literally and flavourfully.</p>`,

  "hot-chocolate-coconut-250g": `<p><strong>Tropical Luxury in Every Sip.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Coconut</strong> brings a smooth, tropical twist to your hot chocolate ritual — premium cacao paired with natural coconut for a creamy, exotic finish.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium coconut drinking chocolate.</li><li><strong>Flavour Profile:</strong> Rich dark chocolate with a smooth, naturally sweet coconut note — creamy and refreshing.</li><li><strong>Preparation:</strong> Best prepared with coconut milk or oat milk for maximum creaminess.</li><li><strong>Dietary:</strong> Naturally dairy-compatible and plant-milk friendly.</li></ul><p><strong>Why Coconut?</strong> A sophisticated, subtropical pairing — coconut softens the intensity of dark chocolate with a smooth, naturally sweet creaminess that feels genuinely indulgent.</p>`,

  "hot-chocolate-strawberry-coconut-250g": `<p><strong>Exotic Shimmer, Coconut Dream.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Sparkle Coconut</strong> elevates our beloved coconut hot chocolate with a magical shimmer effect — rich, tropical, and beautifully luminous in the cup.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium sparkle coconut drinking chocolate with edible shimmer.</li><li><strong>Flavour Profile:</strong> Smooth dark chocolate with a creamy coconut sweetness and a shimmering visual finish.</li><li><strong>Preparation:</strong> Stir into hot milk — watch the shimmer bloom as you pour.</li><li><strong>Best For:</strong> Gifting, special occasions, and anyone who loves a touch of magic in their mug.</li></ul><p><strong>Why Sparkle Coconut?</strong> Because beautiful drinks taste better. This is the hot chocolate you make when you want the moment to feel special.</p>`,

  "hot-chocolate-orange-250g": `<p><strong>A Classic Pairing, Elevated.</strong></p><p><strong>KHOGA Luxury Hot Chocolate – Orange</strong> combines the deep richness of premium dark cacao with the bright, zesty lift of natural orange — a timeless flavour pairing reimagined as a luxury hot drink.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Type:</strong> Premium orange-infused drinking chocolate.</li><li><strong>Flavour Profile:</strong> Intense dark chocolate with a bright, natural orange zest — complex, refined, and deeply warming.</li><li><strong>Preparation:</strong> Stir into hot milk for a silky, café-style orange hot chocolate.</li><li><strong>Best Paired With:</strong> A twist of fresh orange peel on top for extra aroma.</li></ul><p><strong>Why Orange?</strong> Dark chocolate and orange is one of the great classic flavour pairings — vibrant, complex, and surprisingly sophisticated. This is the hot chocolate for those with refined taste.</p>`,

  "coffee-grinder-1": `<p><strong>Stovetop Espresso, Mastered.</strong></p><p>The <strong>KHOGA Moka Pot</strong> is the iconic Italian stovetop coffee maker — engineered to produce rich, full-bodied espresso-style coffee using only water, heat, and finely ground coffee. Simple, reliable, and endlessly satisfying.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Capacity:</strong> 3-cup (approximately 150ml of concentrated coffee).</li><li><strong>Material:</strong> Premium aluminium with a heat-safe handle — lightweight and durable.</li><li><strong>Compatibility:</strong> Works on gas, electric, and ceramic hobs. Not induction-compatible.</li><li><strong>Brew Time:</strong> 4–6 minutes from cold — fast, consistent, and repeatable.</li><li><strong>Maintenance:</strong> Rinse with warm water after each use — no soap needed to preserve the seasoned interior.</li></ul><p><strong>Brewing Tip:</strong> Fill the water chamber just below the safety valve. Use medium-fine ground espresso and never pack the basket too tightly — let the coffee breathe for maximum crema.</p>`,

  "coffee-machine-1": `<p><strong>Traditional Fire, Modern Craft.</strong></p><p>The <strong>Sabrataya – Traditional Copper Spirit Burner</strong> is a beautifully handcrafted tool for authentic Turkish and Arabic coffee brewing. Designed to hold a kanaka or cezve over an open flame — slow, deliberate, and deeply ceremonial.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Hand-hammered copper with artisan detailing.</li><li><strong>Function:</strong> Spirit burner (uses ethanol/methylated spirit) — provides a controlled, adjustable flame for precise coffee brewing.</li><li><strong>Design:</strong> Traditional Middle Eastern form with ornate engravings — a functional piece of cultural art.</li><li><strong>Care:</strong> Wipe with a dry cloth — copper naturally develops a beautiful patina over time.</li></ul><p><strong>Why the Sabrataya?</strong> Brewing Turkish coffee over a spirit burner is not just a method — it's a ritual. The Sabrataya brings that tradition to your home with handcrafted beauty.</p>`,

  "handcrafted-copper-coffee-pot-kanaka": `<p><strong>Handcrafted for the Art of Turkish Coffee.</strong></p><p>The <strong>Kanaka – Handcrafted Copper Coffee Pot</strong> is the traditional vessel for brewing Turkish and Arabic coffee. Hand-hammered from premium copper, each piece is unique — a functional work of art that honours centuries of coffee tradition.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Hand-hammered copper with a tin-lined interior — food safe and flavour neutral.</li><li><strong>Capacity:</strong> 2-cup (approximately 100ml) — perfect for one or two servings.</li><li><strong>Design:</strong> Long handle, flared rim, and tapered body — the classic kanaka silhouette for easy pouring and crema preservation.</li><li><strong>Compatibility:</strong> Works on gas hobs and spirit burners.</li><li><strong>Care:</strong> Hand wash only. Polish occasionally with a copper cleaner to maintain the warm, lustrous finish.</li></ul><p><strong>Why Copper?</strong> Copper is the traditional material for a reason — it heats evenly, responds instantly to temperature changes, and creates the ideal conditions for a slow, controlled Turkish coffee brew.</p>`,

  "the-royal-turkish-brewing-set-handcrafted-copper-spirit-burner-coffee-pot": `<p><strong>The Complete Turkish Coffee Experience.</strong></p><p>The <strong>Royal Turkish Brewing Set</strong> unites our finest handcrafted copper tools into one complete, gift-ready collection. Everything you need to brew and serve authentic Turkish coffee — with ceremony, elegance, and tradition.</p><p><strong>What's Inside:</strong></p><ul><li><strong>Handcrafted Copper Kanaka (Coffee Pot):</strong> Hand-hammered, tin-lined, and designed for precise slow brewing on a spirit burner or gas hob.</li><li><strong>Sabrataya – Copper Spirit Burner:</strong> Traditional burner for controlled, flame-based brewing — the authentic Turkish method.</li><li><strong>Luxury Gift Box:</strong> The full set is presented in our premium KHOGA gift packaging — ready to present as a gift or display at home.</li></ul><p><strong>Why the Royal Set?</strong> For the coffee enthusiast who demands the complete experience — not just the coffee, but the ritual, the tools, and the ceremony. A set that will be used and admired for years.</p>`,

  "handheld-milk-frother": `<p><strong>Café-Quality Foam. Anywhere. Instantly.</strong></p><p>The <strong>KHOGA Handheld Milk Frother</strong> transforms your home coffee into a full café experience — silky microfoam, creamy lattes, and whipped cold foam in under 30 seconds.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Speed:</strong> Creates dense, velvety microfoam in 15–30 seconds.</li><li><strong>Compatibility:</strong> Works with all types of milk — dairy, oat, almond, soy, and more.</li><li><strong>Power:</strong> Battery-operated (2x AA) — no charging required, always ready.</li><li><strong>Build:</strong> Stainless steel whisk with a comfortable, ergonomic grip handle.</li><li><strong>Versatility:</strong> Use for lattes, cappuccinos, matcha, hot chocolate, protein shakes, and dalgona whipped coffee.</li><li><strong>Maintenance:</strong> Run the whisk in clean water for 5 seconds to clean — effortless.</li></ul><p><strong>Why This Frother?</strong> A small tool with a massive impact on your daily coffee quality. The difference between a flat latte and a silky, café-style one — is 20 seconds with this frother.</p>`,

  "burgundy-royal-cup": `<p><strong>Royalty in Every Sip.</strong></p><p>The <strong>Burgundy Royal Cup</strong> is a statement piece — a deep, wine-red porcelain cup designed for those who treat their coffee as a ceremony. Rich in colour, refined in form.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Fine porcelain with a rich burgundy glaze — premium quality and chip-resistant.</li><li><strong>Finish:</strong> Deep, lustrous burgundy with a regal, high-gloss exterior and clean white interior.</li><li><strong>Capacity:</strong> Espresso size — concentrated, intentional, and ceremonial.</li><li><strong>Lifestyle:</strong> The cup you reach for when coffee is a moment, not just a drink.</li></ul><p><strong>Why Burgundy Royal?</strong> Because some mornings deserve a cup that matches the seriousness of your coffee ritual. Bold, beautiful, and unmistakably premium.</p>`,

  "double-glass-espresso-cup": `<p><strong>Watch the Magic Happen.</strong></p><p>The <strong>Double-Glass Espresso Cup</strong> is as much a visual experience as a drinking one. Borosilicate double-wall glass keeps your espresso at the perfect temperature while displaying the layers of your shot in stunning clarity.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Premium borosilicate double-wall glass — heat-resistant and shatterproof.</li><li><strong>Function:</strong> Double-wall insulation keeps espresso hot for longer while the glass stays cool to the touch.</li><li><strong>Capacity:</strong> 80ml — the ideal espresso shot size.</li><li><strong>Aesthetic:</strong> Floating effect — your espresso appears to levitate inside the cup.</li><li><strong>Care:</strong> Dishwasher safe. Microwave safe.</li></ul><p><strong>Why Double Glass?</strong> Because presentation matters. The double-glass cup turns your daily espresso into a visual ritual — watching the crema settle inside the clear walls is genuinely satisfying.</p>`,

  "the-slate-handleless-espresso-cup-pure-edition": `<p><strong>Minimal Form. Maximum Presence.</strong></p><p>The <strong>Slate Handleless Espresso Cup – Pure Edition</strong> is a study in modern minimalism. No handle, no fuss — just a perfectly proportioned, hand-warming vessel for the purist's espresso ritual.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Premium stoneware with a matte slate-grey glaze.</li><li><strong>Form:</strong> Handleless cylindrical cup — inspired by Japanese yunomi tea cups, adapted for espresso.</li><li><strong>Finish:</strong> Smooth matte slate surface — tactile, cool-toned, and beautifully minimal.</li><li><strong>Capacity:</strong> 80ml — precision-sized for a single or double espresso shot.</li><li><strong>Lifestyle:</strong> Perfect for the coffee minimalist — pairs beautifully with natural wood trays and linen napkins.</li></ul><p><strong>Why Handleless?</strong> Wrapping both hands around a warm cup is one of life's small pleasures. The Slate Handleless cup encourages you to slow down, hold on, and savour the moment.</p>`,

  "yellow-glossy-porcelain-set": `<p><strong>A Pop of Joy in Every Cup.</strong></p><p>The <strong>Yellow Glossy Porcelain Set</strong> brings vibrant energy and premium craftsmanship together — a high-gloss, vivid yellow cup-and-saucer set that turns your coffee ritual into a colour-forward statement.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Material:</strong> Fine porcelain — lightweight, non-porous, and ultra-smooth.</li><li><strong>Finish:</strong> High-gloss vibrant yellow — bold, joyful, and striking on any table.</li><li><strong>Set Includes:</strong> Porcelain cup and matching saucer — sold as a complete set.</li><li><strong>Capacity:</strong> Turkish coffee size (approximately 60–80ml) — designed for concentrated brewing.</li><li><strong>Care:</strong> Microwave and dishwasher safe.</li></ul><p><strong>Why Yellow?</strong> Colour changes how coffee tastes — at least psychologically. The Yellow Glossy set brings warmth, optimism, and a touch of playfulness to every cup. Start your morning with a smile.</p>`,

  "black-cozy-mug": `<p><strong>Bold, Warm, Unapologetic.</strong></p><p>The <strong>Black Cozy Mug</strong> is for those who prefer their coffee — and their mugs — with a bit of edge. A deep matte black finish paired with a comfortable, generous form for your most indulgent coffee moments.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Matte black — deep, rich, and fingerprint-resistant.</li><li><strong>Build:</strong> Thick stoneware walls for exceptional heat retention.</li><li><strong>Capacity:</strong> 400ml — large enough for a generous latte or a double-shot americano.</li><li><strong>Handle:</strong> Wide, comfortable loop handle — easy to hold even with both hands wrapped around.</li><li><strong>Lifestyle:</strong> The go-to mug for dark aesthetics, moody mornings, and serious coffee moments.</li></ul>`,

  "fiery-red-cozy-mug": `<p><strong>Passion in a Cup.</strong></p><p>The <strong>Fiery Red Cozy Mug</strong> brings bold energy and warm passion to your daily coffee ritual. A vivid, fiery red finish that demands attention — and delivers comfort.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Fiery red matte glaze — bold, energetic, and beautifully tactile.</li><li><strong>Build:</strong> Premium stoneware with excellent heat retention.</li><li><strong>Capacity:</strong> 400ml — generous and satisfying.</li><li><strong>Handle:</strong> Wide comfort loop — easy to grip and hold securely.</li><li><strong>Lifestyle:</strong> For those who start their morning with intention — and a statement mug to match.</li></ul>`,

  "candy-pink-cozy-mug": `<p><strong>Sweet, Soft, and Totally You.</strong></p><p>The <strong>Candy Pink Cozy Mug</strong> is the playful, cheerful addition your morning routine deserves. A soft, sweet candy-pink glaze with the warmth and comfort of premium stoneware.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Candy pink matte glaze — sweet, soft, and irresistibly cheerful.</li><li><strong>Build:</strong> Premium stoneware — sturdy, heat-retaining, and dishwasher safe.</li><li><strong>Capacity:</strong> 400ml.</li><li><strong>Handle:</strong> Wide, comfortable loop handle.</li><li><strong>Lifestyle:</strong> Perfect for cottagecore aesthetics, pastel kitchen shelves, and anyone who believes mugs should spark joy.</li></ul>`,

  "olive-cozy-mug": `<p><strong>Earthy Calm in Every Sip.</strong></p><p>The <strong>Olive Cozy Mug</strong> brings the grounded tranquility of nature to your coffee moment. A sophisticated olive-green matte glaze that pairs beautifully with natural materials and calm interiors.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Olive green matte glaze — earthy, sophisticated, and deeply calming.</li><li><strong>Build:</strong> Premium stoneware — durable and heat-retaining.</li><li><strong>Capacity:</strong> 400ml.</li><li><strong>Lifestyle:</strong> Ideal for nature-inspired, botanical, or Japandi home aesthetics.</li></ul>`,

  "sky-blue-cozy-mug": `<p><strong>Coffee with a Clear Sky View.</strong></p><p>The <strong>Sky Blue Cozy Mug</strong> is light, fresh, and open — like a clear morning sky. A soft, airy blue glaze that makes every coffee moment feel a little brighter.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Sky blue matte glaze — fresh, airy, and beautifully serene.</li><li><strong>Build:</strong> Premium stoneware — excellent heat retention.</li><li><strong>Capacity:</strong> 400ml.</li><li><strong>Lifestyle:</strong> Perfect for coastal, Scandinavian, or fresh-toned interiors — a mug that feels like a breath of fresh air.</li></ul>`,

  "baby-blue-cozy-mug": `<p><strong>Soft, Gentle, Perfectly Calming.</strong></p><p>The <strong>Baby Blue Cozy Mug</strong> is the softest, most soothing mug in the KHOGA collection. A delicate baby-blue glaze that brings a sense of quiet calm to your morning ritual.</p><p><strong>Key Highlights:</strong></p><ul><li><strong>Finish:</strong> Delicate baby blue matte glaze — soft, gentle, and incredibly soothing.</li><li><strong>Build:</strong> Premium stoneware — sturdy and heat-retaining.</li><li><strong>Capacity:</strong> 400ml.</li><li><strong>Lifestyle:</strong> Perfect for nursery-adjacent aesthetics, pastel lovers, or anyone who starts their day with gentleness.</li></ul>`
};

let updated = 0;
let notFound = 0;

Object.keys(descriptions).forEach(function(handle) {
  const result = db.products.updateOne(
    { handle: handle },
    { $set: { description: descriptions[handle] } }
  );
  if (result.matchedCount > 0) {
    print("✅ " + handle);
    updated++;
  } else {
    print("⚠️  NOT FOUND: " + handle);
    notFound++;
  }
});

print("\n✅ Updated: " + updated + " products");
print("⚠️  Not found: " + notFound + " handles");
